{{- if .Values.commcell}}
apiVersion: v1
kind: Secret
metadata:
  name: commvault-secret-{{ include "mychart.name" . }}
data:
  CV_COMMCELL_USER: {{ .Values.commcell.user }}
  CV_COMMCELL_PWD: {{ .Values.commcell.password }}

{{ end }}

