apiVersion: v1
kind: Service
metadata:
  name: commvault-ma-{{ include "mychart.name" . }}
  labels:
    {{- include "ma_chart.commvault-labels" . | nindent 4 }}
spec:
  ports:
  - port: 8400
    name: cvdport
    targetPort: 8400
  clusterIP: None
  selector:
    {{- include "ma_chart.commvault-labels" . | nindent 4 }}
