{{- if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: commvault-registry-creds-{{ include "mychart.name" . }}
  lables:
  {{- include "ma_chart.commvault-labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "ma-chart.imagePullSecret" . }}

{{ end }}
