---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-pvc
  labels:
    app: nginx-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Pod
metadata:
  name: automation-pod
  labels:
    app: nginx-test
spec:
  containers:
   - name: web-server
     image: nginx:latest
     volumeMounts:
       - name: mypvc
         mountPath: /tmp
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: automation-pvc
       readOnly: false

