Function Main()
{
    $PWD = "##Automation--LoginPassword--##"
    $Email = "##Automation--LoginUser--##"
    $GroupName = "##Automation--GroupName--##"

    $SecurePassword = ConvertTo-SecureString -String $PWD -AsPlainText -Force

    $Credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $Email, $SecurePassword

	# $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Credential -Authentication Basic -AllowRedirection

    # Import-PSSession $Session -DisableNameChecking -AllowClobber | Out-Null

    Connect-ExchangeOnline -Credential $Credential -ShowBanner:$false
    
    $users = Get-UnifiedGroup -Identity $GroupName | Get-UnifiedGroupLinks -LinkType Member | Where-Object {$_.RecipientType -eq "UserMailbox"} | Select-Object Name |  Where-Object { $_.Name -NotLike "CVEXBackupAccount*" -And $_.Name -NotLike "CommvaultAutoGenerated*"}

    $User_Count = $users.count

#    Remove-PSSession $Session

    return $User_Count
}