# -*- coding: utf-8 -*-

# --------------------------------------------------------------------------
# Copyright Commvault Systems, Inc.
# See LICENSE.txt in the project root for
# license information.
# --------------------------------------------------------------------------

"""
File that contains list of constants used by  admin console pages objects and test cases
"""
from enum import Enum


class InternetOptions(Enum):
    """
    Enum with list of all options available under Internet Options in Maintainence tab.
    """
    NO_GATEWAY = "No gateway"
    USE_METRIC_SERVER = "Use Metrics Server"
    USE_CLIENT = "Use client"


class DownloadOptions(Enum):
    """
    Enum with list of all options available under Download software in Maintainence tab.
    """
    LATEST_SP = "servicePack"
    LATEST_HF_FOR_INSTALLED_SP = "hotFixes"
    GIVEN_SP_AND_HF = "servicePackAndHotfixes"


class Packages(Enum):
    """
    Enum with list of packages names in the install/uninstall dropdown
    """
    MEDIA_AGENT = "Media Agent"
    FILE_SYSTEM_CORE = "File System Core"
    FILE_SYSTEM = "File System"
    ORACLE = "Oracle"
    COMMAND_CENTER = "Command Center"
    CONTENT_EXTRACTOR = "Content Extractor"
    INDEX_GATEWAY = "Index Gateway"
    INDEX_STORE = "Index Store"
    MESSAGE_QUEUE = "Message Queue"
    METRICS_REPORTING = "Metrics Reporting"
    METRICS_REPORTING_DB = "Metrics Reporting DB"
    MONGO_DB = "Mongo DB"
    VIRTUAL_SERVER = "Virtual Server"
    VSS_PROVIDER = "VSS Provider"
    VSS_HARDWARE_PROVIDER = "VSS Hardware Provider"
    WEB_SERVER = "Web Server"


class DownloadOS(Enum):
    """
    List of supported OS groups.
    """
    WINDOWS_32 = "Windows(32)"
    WINDOWS_64 = "Windows(X64)"
    UNIX_AIX = "Aix PPC"
    UNIX_AIX32 = "Aix-PPC-32"
    UNIX_MAC = "macOS"
    UNIX_FREEBSD86 = "Freebsd X86"
    UNIX_FREEBSD64 = "Freebsd X86_64"
    UNIX_HP = "HP IA64"
    UNIX_LINUX86 = "Linux X86"
    UNIX_LINUX64 = "Linux X86_64"
    UNIX_S390 = "Linux-S390"
    UNIX_S390_31 = "Linux-S390-31"
    UNIX_PPC64 = "Linux-PPC-64"
    UNIX_SOLARIS86 = "Solaris X86"
    UNIX_SOLARIS64 = "Solaris X86_64"
    UNIX_SOLARIS_SPARC = "Solaris SPARC"
    UNIX_SOLARIS_SPARC86 = "Solaris-SPARC-X86"


class DownloadOSID(Enum):
    """
    List of supported OS groups.
    """
    WINDOWS_32 = "Windows(32)"
    WINDOWS_64 = "Windows(X64)"
    UNIX_AIX = "AIX PPC"
    UNIX_AIX32 = "Aix-PPC-32"
    UNIX_AIX52_32 = "AIX52-32"
    UNIX_MAC = "macOS"
    UNIX_FREEBSD86 = "Freebsd X86"
    UNIX_FREEBSD64 = "Freebsd X86_64"
    UNIX_HP = "HP IA64"
    UNIX_LINUX86 = "Linux X86"
    UNIX_LINUX64 = "Linux X86_64"
    UNIX_S390 = "Linux-S390"
    UNIX_S390_31 = "Linux-S390-31"
    UNIX_PPC64 = "Linux PPC64"
    UNIX_PPC64le = "Linux PPC64le"
    UNIX_SOLARIS86 = "Solaris X86"
    UNIX_SOLARIS64 = "Solaris X86_64"
    UNIX_SOLARIS_SPARC = "Solaris SPARC"
    UNIX_SOLARIS_SPARC86 = "Solaris-SPARC-X86"
    UNIX_LINUX_ARM64 = "Linux ARM64"


class LocaleFile(Enum):
    """
    List of all pages and its locale file names
    """
    _Navigator = "capps, browse, navJs, messagesJs, messages, vmsJs, collections, settingsJs, actions, users, " \
        + "clients, devices, alerts"
    AddDBInstance = "dbs, ediscovery, postgres"
    Agents = "navJs"
    AlertDefinitions = "navJs"
    Alerts = "navJs"
    AlertsDefinitionsInfo = "navJs"
    ArrayDetails = "navJs"
    Arrays = "snapArray"
    Backupset = "ediscovery, postgres, capps"
    PostgreSQLBackupset = "dbs, postgres"
    DB2Backupset = "dbs, db2, Browse"
    Commcell = "sendLogs, settings, security, clients, subscriptions, messages, profiles, settingsJs"
    DBInstance = "navJs"
    DBInstances = "mySql, databaseClone, oracle, informix, sybase, postgres, dbs, capps, servers"
    DBInstanceDetails = "saphana, sqlserver, ediscovery, postgres"
    RDatabasesMetallic = "kubernetes, servers, dr, storage, postgres, mySql"
    SubClient = "nas"
    Domains = "navJs"
    BackupSets = "navJs"
    Subclients = "navJs"
    GlobalExceptions = "navJs"
    Jobs = "job, storage, messagesJs, fs, profiles"
    JobDetails = "job, messagesJs, fs, profiles"
    KeyManagementServers = "security"
    Maintenance = "navJs, settings, schedule, users"
    OperationWindow = "navJs"
    PlanDetails = "profiles, navJs"
    Plans = "profiles, ediscovery, storage"
    Roles = "navJs"
    ServerDetails = "navJs"
    ServerGroups = "navJs"
    Servers = "navJs, users, settings, servers, serversJs"
    Laptops = "navJs, devices, restore, messages"
    Settings = "navJs"
    SNMPConfiguration = "navJs"
    SubclientPolicies = "navJs"
    SubclientPolicyDetails = "navJs"
    SubclientPolicySubclientDetails = "navJs"
    StoragePolicies = "navJs"
    StoragePolicyDetails = "navJs"
    DiskStorage = "storage, subscriptions"
    DiskStorageDetails = "storage, subscriptions"
    MediaAgentDetails = "storage"
    DiskBackupLocation = "storage, subscriptions"
    CloudStorage = "storage, subscriptions"
    CloudStorageDetails = "storage, subscriptions"
    CloudContainerDetails = "storage, subscriptions"
    AirGapProtectStorage = "storage, subscriptions"
    AirGapProtectStorageDetails = "storage, subscriptions"
    AirGapProtectContainer = "storage, subscriptions"
    StorageOnboardingSaaS = "storage, subscriptions, kubernetes"
    SubclientDetails = "navJs"
    TriggeredAlerts = "navJs"
    Users = "users, usersJs"
    UserDetails = "users, usersJs"
    BackupsetLevel = "navJs"
    ClientDetails = "navJs"
    FileSystem = "navJs"
    FsAgent = "fs"
    FsBackupset = "navJs"
    FsSubclient = "fs"
    FsSubclientDetails = "ServersJS, fs, restore, collectionsJs, servers"
    FileServers = "ServersJS, fs, clients, servers , devices, profiles, settings, setup, messages, archiving"
    NASFileServers = "ServersJS, fs, clients, servers , devices, profiles, settings, setup, messages, archiving"
    AddPanel = "ServersJS, fs"
    iDA = "navJs"
    Restores = "navJs"
    RestoreSelectVolume = "navJs"
    Subclient = "navJs"
    NASTemplate = "settings, nas"
    DataSourceDiscover = "ediscovery"
    DataSourceReview = "ediscovery, exchange"
    FileServerLookup = "ediscovery, exchange"
    FileStorageOptimization = "ediscovery"
    FileStorageOptimizationClientDetails = "ediscovery"
    FsoDataSourceDiscover = "ediscovery"
    FsoDataSourceReview = "ediscovery"
    FsoDataSourceDetails = "ediscovery"
    FsoServerGroupDetails = "ediscovery"
    ReviewRequest = "ediscovery"
    GovernanceApps = "ediscovery"
    CaseManager = "exchange"
    EntityManager = "ediscovery"
    EntityTags = "tags"
    ClassifierManager = "ediscovery,profiles"
    InventoryManager = "ediscovery"
    InventoryManagerDetails = "ediscovery"
    SensitiveDataAnalysis = "ediscovery"
    SensitiveDataAnalysisProjectDetails = "ediscovery"
    DiskLevelRestore = "navJs,restoreJs"
    FullVMRestore = "collectionsJs"
    GuestFilesRestoreSelectFolder = "navJs, restore, userPermissions"
    GuestFilesRestoreSelectVolume = "navJs"
    EndUserGuestFilesRestoreSelectFolder = "navJs, restore"
    EndUserFullVMRestore = "navJs, serversJs"
    HypervisorDetails = "vmsJs, servers, settings, clients, vmManagement, serversJs"
    Hypervisors = "settings, navJs, servers"
    ManageContent = "navJs, users"
    Report = "ReportsPlusMessages"
    ManageReport = "navJs"
    ReplicationTargetDetails = "navJs, replicationGroups"
    ReplicationTargets = "navJs, replicationGroups"
    ReplicationMain = "navJs, vmsJs, dr, servers, storage"
    ContinuousReplicationMonitor = "dr, blrJs, messagesJs"
    RestoreSelectVM = "navJs"
    SelectRestore = "navJs, restore"
    VirtualMachineFilesRestore = "navJs"
    VMGroups = "navJs, dr"
    VMStatus = "navJs"
    VirtualMachines = "vms, vmsJs, dr"
    VMDetails = "vms, vmsJs, dr"
    VsaSearchRestore = "navJs"
    VsaSubclientDetails = "navJs, vmsJs, serversJs, dr"
    Dashboard = "reports"
    ConfigureBLR = "fs"
    ReplicaCopy = "fs"
    RecoveryPointStore = "storage, vmsJs, settings"
    RecoveryPointStoreTab = "storage, vmsJs"
    RPStores = "storage, vmsJs"
    RpstoreOperations = "storage, vmsJs, settingsJs, blrJs"
    RConfigureRPStore = "profiles, schedule"
    PairDetailsOperations = "storage, vmsJs, settingsJs, blrJs"
    ConfigureVSAReplicationGroup = "navJs"
    ConfigureReplicationGroup = "navJs"
    SQLServerReplication = "navJs"
    SQLInstances = "sqlServerInstance"
    SQLInstance = "sqlServerInstance"
    ManageSchedules = "reports"
    ConfigureSchedules = "reports"
    Tag = "reports"
    IdentityServers = "users"
    IdentityServerDetails = "users"
    Virtualization = "profiles, settings, servers, devices, setup"
    GettingStarted = "setup, messages"
    MediaAgents = "navJs, users, storage"
    CommonFeatures = "reports"
    Table = "reports"
    ManageAlerts = "reports"
    Instances = "bigData"
    CassandraServer = "bigData"
    SplunkServer = "bigData"
    Configuration = "bigData"
    Overview = "bigData"
    Restore = "bigData"
    Archiving = "navJs"
    PermissionReport = "ediscovery"
    RequestManager = "ediscovery"
    DomainDetails = "navJs"
    CredentialManager = "navJs"
    Theme = "navJs"
    ObjectStorage = "cloudStorageApp, cloudStorageAppJs"
    Browse = "restore, browse"
    RBrowse = "restore, browse, settings, BackupBrowseMessages"
    EmailHeaderFooter = 'navJs'
    EmailTemplates = 'navJs'
    LiveMount = "navJs"
    Office365Apps = "office365, exchange, sharepoint"
    Kubernetes = "profiles, settings, servers, setup, actions, kubernetes"
    KubernetesSetup = "profiles, settings, servers, setup, actions, kubernetes"
    KubernetesHub = "profiles, settings, servers, setup, actions, kubernetes"
    K8sHelper = "profiles, settings, servers, setup, actions, kubernetes"
    KubernetesRestore = "profiles, settings, servers, setup, actions, kubernetes, restore"
    AppGroupDetails = "settings, navJs, actions, restore, kubernetes"
    AppGroups = "kubernetes, settings"
    K8sClusters = "profiles, settings, setup, kubernetes, actions"
    AddK8sCluster = "profiles, settings, setup, kubernetes, actions"
    K8sAppGroup = "profiles, kubernetes"
    NetworkStoreHelper = "storage"
    DRBackupDaily = "settings, storage"
    ServiceCommcell = "actions, settings"
    SalesforceAppDetails = "settings"
    SalesforceRestore = "restore"
    SalesforceDashboard = "capps"
    Dynamics365Apps = "office365, exchange"
    FailoverGroup = "dr"
    Tags = "ediscovery"
    Companies = "subscriptions"
    NetworkPage = "network, navJs, actions"
    RAlertDefinitions = "alerts"
    Ralerts = "alerts"
    AlertRules = "alerts"
    GCMHelper = "commcell, securityDashboard, messagesJs, settings"
    GlobalSearchHelper = "clients,settings,subscriptions,actions,deviceDetails,replicationGroups,job,sendLogs"

    # DR, Auto Recovery and CleanRoom Recovery
    _AWSRecoveryTarget = "restore, dr, storage, migration"
    _AzureRecoveryTarget = "restore, dr, migration"
    _ConfigureCommon = "messages, collectionsJs, replicationGroups, restoreJs"
    _HyperVRecoveryTarget = "restore, dr"
    _ReplicationGroupCommonConfig = "dr, restore"
    _VMwareVMOptions = "restore, dr"
    AdvancedTab = "dr"
    ConfigurationTab = "profiles, replicationGroups, serversJs, restore"
    EditVirtualMachine = "restore"
    MonitorTab = "replicationGroups, profiles"
    OverviewTab = "replicationGroups, profiles"
    ReplicationDetails = "replicationGroups,dr,vmManagementJs"
    ReplicationGroup = "replicationGroups"
    ReplicationGroupDetails = "navJs, job"
    ReplicationHelper = "vmsJs, dr, replicationGroups, serversJs, restore, collectionsJs"
    ReplicationMonitor = "replicationGroups, dr"
    RtargetDetails = "servers"
    TestFailoverVMs = "vmManagementJs"
    RecoveryTargets = "vmManagementJs"
    NavigationPreferences = "navJs, ediscovery, dr"


class ConsoleTypes(Enum):
    """
        List of console types and its corresponding base url
    """
    CLOUD_CONSOLE = "%s://%s/cloudconsole/"
    COMMAND_CENTER = "%s://%s/commandcenter/"
    ADMIN_CONSOLE = "%s://%s/adminconsole/"
    WEB_CONSOLE = "%s://%s/webconsole/"
