galaxy_info:
  author: Commvault Systems, Inc.
  description: File System Deployment
  company: Commvault Systems, Inc. 

  license: Apache-2.0

  min_ansible_version: 2.12

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  